import AdminTable from "@/components/admin/AdminTable";
import { OrderFulfillment } from "@/components/admin/AdminActions";
import { getAdminData, getQuery } from "@/lib/admin/server";
import type { AdminOrder, PageResponse } from "@/lib/admin/types";
import { Link } from "@/i18n/navigation";
import { setRequestLocale } from "next-intl/server";

export default async function Page({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { locale } = await params; setRequestLocale(locale);
  const data = await getAdminData<PageResponse<AdminOrder>>(`/orders?${getQuery(await searchParams)}`);
  const field = "rounded-lg border border-gray-300 bg-transparent px-3 py-2 text-sm dark:border-gray-700";
  return <AdminTable title="Pedidos" data={data} filters={<><select name="status" className={field}><option value="">Todos os status</option><option>CRIADO</option><option>AGUARDANDO_PAGAMENTO</option><option>ABANDONADO</option><option>PAGO</option><option>PROCESSADO</option><option>SEPARADO</option><option>PREPARANDO</option><option>ENVIADO</option><option>ENTREGUE</option><option>CANCELADO</option><option>REEMBOLSADO</option></select><input name="customerId" placeholder="ID do cliente" className={field} /><input name="dataInicio" type="date" className={field} /><input name="dataFim" type="date" className={field} /></>} rowClassName={(item) => item.status === "ENTREGUE" ? "bg-success-50/60 dark:bg-success-500/10" : item.status === "CANCELADO" ? "bg-error-50/60 dark:bg-error-500/10" : item.status === "REEMBOLSADO" ? "bg-orange-50/70 dark:bg-orange-500/10" : ""} columns={[{ label: "Pedido", value: (item) => <Link href={`/ecommerce/orders/${item.orderId}`} className="font-medium text-brand-500">#{item.orderId}</Link> }, { label: "Usuário", value: (item) => item.customer.nomeCompleto }, { label: "E-mail", value: (item) => item.customer.email }, { label: "Quantidade", value: (item) => item.items.reduce((total, product) => total + product.quantidade, 0) }, { label: "Total", value: (item) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(item.valorTotal) }, { label: "Status", value: (item) => item.status }, { label: "Ação", value: (item) => item.status === "ENTREGUE" && item.customer.telefone ? <a href={`https://wa.me/${item.customer.telefone.replace(/\D/g, "")}`} target="_blank" rel="noreferrer" className="rounded-lg bg-success-500 px-3 py-2 text-xs font-semibold text-white">WhatsApp</a> : <OrderFulfillment id={item.orderId} status={item.status} /> }]} />;
}
