"use client";

import { useEffect, useState } from "react";
import Alert from "@/components/ui/alert/Alert";
import type { AdminBrand } from "@/lib/admin/types";

type Form = { name: string; slug: string };
type Notice = { variant: "success" | "error"; title: string; message: string };
const empty: Form = { name: "", slug: "" };
export default function BrandManager() {
  const [items, setItems] = useState<AdminBrand[]>([]); const [form, setForm] = useState<Form>(empty); const [editing, setEditing] = useState<AdminBrand | null>(null); const [notice, setNotice] = useState<{ variant: "success" | "error"; title: string; message: string } | null>(null);
  const show = (notice: Notice) => { setNotice(notice); window.setTimeout(() => setNotice(null), 5000); };
  async function load() { const r = await fetch("/api/commerce/admin/brands"); if (r.ok) setItems(await r.json()); else show({ variant: "error", title: "Marcas indisponíveis", message: await message(r) }); }
  useEffect(() => { void load(); }, []);
  async function create() { const r = await fetch("/api/commerce/admin/brands", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!r.ok) return show({ variant: "error", title: "Não foi possível cadastrar", message: await message(r) }); setForm(empty); show({ variant: "success", title: "Marca cadastrada", message: "A marca foi cadastrada." }); await load(); }
  async function update(patch: Partial<AdminBrand>) { if (!editing) return; const r = await fetch(`/api/commerce/admin/brands/${editing.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); if (!r.ok) return show({ variant: "error", title: "Não foi possível atualizar", message: await message(r) }); setEditing(null); show({ variant: "success", title: "Marca atualizada", message: "As alterações foram salvas." }); await load(); }
  const input = "mt-1 w-full rounded-lg border border-gray-300 bg-transparent px-3 py-2 text-sm dark:border-gray-700";
  return <div className="space-y-6"><section className="rounded-xl border border-gray-200 bg-white p-5 dark:border-white/[0.05] dark:bg-white/[0.03]"><h2 className="mb-4 font-semibold">Nova marca</h2><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Nome" className={input} /><input value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} placeholder="Slug" className={input} /><button type="button" onClick={() => void create()} className="rounded-lg bg-brand-500 px-4 py-2 text-sm font-semibold text-white">Cadastrar</button></div></section><section className="rounded-xl border border-gray-200 bg-white p-5 dark:border-white/[0.05] dark:bg-white/[0.03]"><div className="overflow-x-auto"><table className="min-w-full"><thead><tr className="text-left text-sm text-gray-500"><th>Nome</th><th>Slug</th><th>Status</th><th>Atualização</th><th className="text-right">Ações</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-gray-100 dark:border-white/[0.05]"><td className="py-3 font-medium">{item.name}</td><td>{item.slug}</td><td>{item.ativo ? "Ativa" : "Inativa"}</td><td>{item.dataAtualizacao}</td><td className="text-right"><button type="button" onClick={() => setEditing(item)} className="text-brand-500">Editar</button></td></tr>)}</tbody></table></div></section>{notice && <div className="fixed right-5 top-5 z-[100000] w-[min(24rem,calc(100vw-2.5rem))]"><Alert {...notice} /></div>}{editing && <div className="fixed inset-0 z-99999 flex items-center justify-center bg-gray-950/60 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5 dark:bg-gray-900"><h2 className="mb-4 font-semibold">Editar marca</h2><label className="text-sm">Nome<input value={editing.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })} className={input} /></label><label className="mt-3 block text-sm">Slug<input value={editing.slug} onChange={(e) => setEditing({ ...editing, slug: e.target.value })} className={input} /></label><label className="mt-3 block text-sm">Status<select value={editing.ativo ? "true" : "false"} onChange={(e) => setEditing({ ...editing, ativo: e.target.value === "true" })} className={input}><option value="true">Ativa</option><option value="false">Inativa</option></select></label><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={() => setEditing(null)}>Cancelar</button><button type="button" onClick={() => void update({ name: editing.name, slug: editing.slug, ativo: editing.ativo })} className="rounded-lg bg-brand-500 px-4 py-2 text-white">Salvar</button></div></div></div>}</div>;
}
async function message(r: Response) { const t = await r.text(); try { const j = JSON.parse(t); return j.message ?? j.detail ?? j.error ?? "A operação não foi concluída."; } catch { return t || "A operação não foi concluída."; } }
