"use client";
import { useRef, useState } from "react";
import { useRouter } from "@/i18n/navigation";
import Alert from "@/components/ui/alert/Alert";

type Notice = { variant: "success" | "error"; title: string; message: string };
type Option = { id: number; name: string; ativo?: boolean; categoryId?: number };
const fieldLabels: Record<string, string> = { nome: "Nome", slug: "Slug", descricaoCurta: "Descrição curta", descricao: "Descrição", preco: "Preço", precoPromocional: "Preço promocional", quantidadeEstoque: "Quantidade em estoque", estoqueMinimo: "Estoque mínimo", sku: "SKU", peso: "Peso", altura: "Altura", largura: "Largura", comprimento: "Comprimento" };
const required = ["nome", "slug", "descricaoCurta", "descricao", "preco", "quantidadeEstoque", "estoqueMinimo", "sku", "peso", "altura", "largura", "comprimento"];
const initial = Object.fromEntries([...Object.keys(fieldLabels).map((key) => [key, ""]), ["categoriaId", ""], ["brandId", ""], ["status", "ATIVO"]]) as Record<string, string>;

export default function ProductAdminTools() {
 const router = useRouter(); const importRef = useRef<HTMLInputElement>(null); const [open, setOpen] = useState(false); const [data, setData] = useState(initial); const [categories, setCategories] = useState<Option[]>([]); const [brands, setBrands] = useState<Option[]>([]); const [notice, setNotice] = useState<Notice | null>(null);
 const show = (item: Notice) => { setNotice(item); window.setTimeout(() => setNotice(null), 5000); }; const input = "mt-1 w-full rounded-lg border border-gray-300 bg-transparent px-3 py-2 dark:border-gray-700";
 async function openForm() { const [categoriesResult, brandsResult] = await Promise.all([fetch("/api/commerce/categories?name="), fetch("/api/commerce/admin/brands")]); if (categoriesResult.ok) setCategories(await categoriesResult.json()); if (brandsResult.ok) setBrands((await brandsResult.json()).filter((brand: Option) => brand.ativo)); setOpen(true); }
 async function submit() { const blank = required.find((key) => !data[key].trim()); if (blank) return show({ variant: "error", title: "Revise o formulário", message: `${fieldLabels[blank]} é obrigatório.` }); const body = Object.fromEntries(Object.entries(data).map(([key, value]) => [key, (key === "categoriaId" || key === "brandId") && !value ? null : value])); const result = await fetch("/api/commerce/admin/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!result.ok) return show({ variant: "error", title: "Não foi possível cadastrar", message: await message(result) }); setOpen(false); setData(initial); show({ variant: "success", title: "Produto cadastrado", message: "O produto foi cadastrado com sucesso." }); router.refresh(); }
 async function importCsv(file: File) { const body = new FormData(); body.append("file", file); const result = await fetch("/api/commerce/admin/imports/products", { method: "POST", body }); if (!result.ok) return show({ variant: "error", title: "Falha na importação", message: await message(result) }); show({ variant: "success", title: "Importação concluída", message: "Arquivo processado com sucesso." }); router.refresh(); }
 return <><div className="mb-4 flex flex-wrap justify-end gap-3"><input ref={importRef} type="file" accept=".csv,text/csv" className="sr-only" onChange={(e) => { const file = e.target.files?.[0]; if (file) void importCsv(file); }} /><button type="button" onClick={() => importRef.current?.click()} className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold dark:border-gray-700">Importar CSV</button><button type="button" onClick={() => void openForm()} className="rounded-lg bg-brand-500 px-4 py-2 text-sm font-semibold text-white">Novo produto</button></div>{notice && <div className="fixed right-5 top-5 z-[100000] w-[min(24rem,calc(100vw-2.5rem))]"><Alert {...notice} /></div>}{open && <div className="fixed inset-0 z-99999 flex items-center justify-center bg-gray-950/60 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 dark:bg-gray-900"><div className="mb-5 flex justify-between"><div><h2 className="font-semibold">Cadastrar produto</h2><p className="text-sm text-gray-500"><span className="text-error-500">*</span> Campos obrigatórios</p></div><button type="button" onClick={() => setOpen(false)}>×</button></div><div className="grid gap-4 sm:grid-cols-2">{Object.entries(fieldLabels).map(([key, label]) => <label key={key} className="text-sm font-medium">{label}{required.includes(key) && <span className="ms-1 text-error-500">*</span>}<input type={["preco", "precoPromocional", "quantidadeEstoque", "estoqueMinimo", "peso", "altura", "largura", "comprimento"].includes(key) ? "number" : "text"} step="any" value={data[key]} onChange={(e) => setData({ ...data, [key]: e.target.value })} className={input} /></label>)}<label className="text-sm font-medium">Categoria<select value={data.categoriaId} onChange={(e) => setData({ ...data, categoriaId: e.target.value })} className={input}><option value="">Nenhuma categoria</option>{categories.map((item) => <option key={item.categoryId} value={item.categoryId}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Marca<select value={data.brandId} onChange={(e) => setData({ ...data, brandId: e.target.value })} className={input}><option value="">Nenhuma marca</option>{brands.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Status<span className="ms-1 text-error-500">*</span><select value={data.status} onChange={(e) => setData({ ...data, status: e.target.value })} className={input}><option>ATIVO</option><option>INATIVO</option><option>SEM_ESTOQUE</option></select></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)}>Cancelar</button><button type="button" onClick={() => void submit()} className="rounded-lg bg-brand-500 px-4 py-2 text-white">Cadastrar</button></div></div></div>}</>;
}
async function message(response: Response) { const raw = await response.text(); try { const json = JSON.parse(raw); return json.message ?? json.detail ?? json.error ?? "A operação não foi concluída."; } catch { return raw || "A operação não foi concluída."; } }
