"use client";

import { useRef, useState } from "react";
import { useRouter } from "@/i18n/navigation";

export default function ProductAdminTools() {
  const router = useRouter();
  const inputRef = useRef<HTMLInputElement>(null);
  const [message, setMessage] = useState("");
  const [open, setOpen] = useState(false);
  const [data, setData] = useState<Record<string, string>>({ nome: "", slug: "", descricaoCurta: "", descricao: "", preco: "", precoPromocional: "", quantidadeEstoque: "", estoqueMinimo: "", sku: "", peso: "", altura: "", largura: "", comprimento: "", categoriaId: "", status: "ATIVO" });
  const [categories, setCategories] = useState<Array<{ categoryId: number; name: string }>>([]);
  const fields = ["nome", "slug", "descricaoCurta", "descricao", "preco", "precoPromocional", "quantidadeEstoque", "estoqueMinimo", "sku", "peso", "altura", "largura", "comprimento"];
  async function openCreate() { const response = await fetch("/api/commerce/categories?name="); if (response.ok) setCategories(await response.json()); setOpen(true); }
  async function create() { const body = Object.fromEntries(Object.entries(data).filter(([key, value]) => value !== "" || key === "status")); const response = await fetch("/api/commerce/admin/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (response.ok) { setOpen(false); router.refresh(); } else setMessage("Não foi possível cadastrar o produto. Revise os campos obrigatórios."); }
  async function importCsv(file: File) { const form = new FormData(); form.append("file", file); const response = await fetch("/api/commerce/admin/imports/products", { method: "POST", body: form }); setMessage(response.ok ? "Arquivo processado com sucesso." : "Não foi possível importar o arquivo."); if (response.ok) router.refresh(); }
  return <><div className="mb-4 flex flex-wrap justify-end gap-3"><input ref={inputRef} type="file" accept=".csv,text/csv" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importCsv(file); }} /><button type="button" onClick={() => inputRef.current?.click()} className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold dark:border-gray-700">Importar CSV</button><button type="button" onClick={() => void openCreate()} className="rounded-lg bg-brand-500 px-4 py-2 text-sm font-semibold text-white">Novo produto</button></div>{message && <p className="mb-3 text-sm text-brand-600">{message}</p>}{open && <div className="fixed inset-0 z-99999 flex items-center justify-center bg-gray-950/60 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 dark:bg-gray-900"><div className="mb-4 flex justify-between"><h2 className="font-semibold">Cadastrar produto</h2><button type="button" onClick={() => setOpen(false)}>×</button></div><div className="grid gap-3 sm:grid-cols-2">{fields.map((field) => <label key={field} className="text-sm">{field}<input value={data[field]} onChange={(event) => setData({ ...data, [field]: event.target.value })} className="mt-1 w-full rounded-lg border border-gray-300 bg-transparent px-3 py-2 dark:border-gray-700" /></label>)}<label className="text-sm">Categoria<select value={data.categoriaId} onChange={(event) => setData({ ...data, categoriaId: event.target.value })} className="mt-1 w-full rounded-lg border border-gray-300 bg-transparent px-3 py-2 dark:border-gray-700"><option value="">Selecione uma categoria</option>{categories.map((category) => <option key={category.categoryId} value={category.categoryId}>{category.name}</option>)}</select></label><label className="text-sm">Status<select value={data.status} onChange={(event) => setData({ ...data, status: event.target.value })} className="mt-1 w-full rounded-lg border border-gray-300 bg-transparent px-3 py-2 dark:border-gray-700"><option>ATIVO</option><option>INATIVO</option><option>SEM_ESTOQUE</option></select></label></div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)}>Cancelar</button><button type="button" onClick={() => void create()} className="rounded-lg bg-brand-500 px-4 py-2 text-white">Cadastrar</button></div></div></div>}</>;
}
