"use client";
import { useState } from "react";
import { useRouter } from "@/i18n/navigation";
import Alert from "@/components/ui/alert/Alert";
type Option = { id: number; name: string; ativo?: boolean; categoryId?: number };
const labels: Record<string, string> = { nome: "Nome", slug: "Slug", descricaoCurta: "Descrição curta", descricao: "Descrição", preco: "Preço", precoPromocional: "Preço promocional", estoqueMinimo: "Estoque mínimo", peso: "Peso", altura: "Altura", largura: "Largura", comprimento: "Comprimento" };
export default function ProductEditButton({ id }: { id: number }) {
 const router = useRouter(); const [open,setOpen]=useState(false); const [data,setData]=useState<Record<string,string>>({}); const [original,setOriginal]=useState<Record<string,string>>({}); const [categories,setCategories]=useState<Option[]>([]); const [brands,setBrands]=useState<Option[]>([]); const [notice,setNotice]=useState<{variant:"success"|"error";title:string;message:string}|null>(null); const input="mt-1 w-full rounded-lg border border-gray-300 bg-transparent px-3 py-2 dark:border-gray-700";
 const show=(n:NonNullable<typeof notice>)=>{setNotice(n);window.setTimeout(()=>setNotice(null),5000)};
 async function openEditor(){const [product,categoriesResult,brandsResult]=await Promise.all([fetch(`/api/commerce/products/${id}`),fetch("/api/commerce/categories?name="),fetch("/api/commerce/admin/brands")]);if(!product.ok)return show({variant:"error",title:"Produto indisponível",message:await message(product)});const value=Object.fromEntries(Object.entries(await product.json()).map(([key,value])=>[key,value==null?"":String(value)]));setData(value);setOriginal(value);if(categoriesResult.ok)setCategories(await categoriesResult.json());if(brandsResult.ok)setBrands(await brandsResult.json());setOpen(true)}
 async function save(){const body:Record<string,unknown>={};for(const key of Object.keys(labels)){if(data[key]!==original[key])body[key]=data[key]||null}if(data.status!==original.status)body.status=data.status;for(const [idKey,removeKey] of [["categoriaId","removeCategory"],["brandId","removeBrand"]] as const){if(data[idKey]===original[idKey])continue;if(data[idKey])body[idKey]=Number(data[idKey]);else if(original[idKey])body[removeKey]=true}const result=await fetch(`/api/admin/products/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!result.ok)return show({variant:"error",title:"Não foi possível atualizar",message:await message(result)});setOpen(false);show({variant:"success",title:"Produto atualizado",message:"As alterações foram salvas."});router.refresh()}
 return <><button type="button" onClick={()=>void openEditor()} title="Editar produto" aria-label="Editar produto" className="text-brand-500">✎</button>{notice&&<div className="fixed right-5 top-5 z-[100000] w-[min(24rem,calc(100vw-2.5rem))]"><Alert {...notice}/></div>}{open&&<div className="fixed inset-0 z-99999 flex items-center justify-center bg-gray-950/60 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 dark:bg-gray-900"><div className="mb-5 flex justify-between"><h2 className="font-semibold">Editar produto</h2><button type="button" onClick={()=>setOpen(false)}>×</button></div><div className="grid gap-4 sm:grid-cols-2">{Object.entries(labels).map(([key,label])=><label key={key} className="text-sm font-medium">{label}<input value={data[key]??""} onChange={(e)=>setData({...data,[key]:e.target.value})} className={input}/></label>)}<label className="text-sm font-medium">Categoria<select value={data.categoriaId??""} onChange={(e)=>setData({...data,categoriaId:e.target.value})} className={input}><option value="">Nenhuma categoria</option>{categories.map((item)=><option key={item.categoryId} value={item.categoryId}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Marca<select value={data.brandId??""} onChange={(e)=>setData({...data,brandId:e.target.value})} className={input}><option value="">Nenhuma marca</option>{brands.map((item)=><option key={item.id} value={item.id}>{item.name}{item.ativo===false?" (inativa)":""}</option>)}</select></label><label className="text-sm font-medium">Status<select value={data.status??"ATIVO"} onChange={(e)=>setData({...data,status:e.target.value})} className={input}><option>ATIVO</option><option>INATIVO</option><option>SEM_ESTOQUE</option></select></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button type="button" onClick={()=>void save()} className="rounded-lg bg-brand-500 px-4 py-2 text-white">Salvar</button></div></div></div>}</>;
}
async function message(response:Response){const raw=await response.text();try{const json=JSON.parse(raw);return json.message??json.detail??json.error??"A operação não foi concluída."}catch{return raw||"A operação não foi concluída."}}
