import ProductInventoryAndImages from "@/components/admin/ProductInventoryAndImages";
import ComponentCard from "@/components/common/ComponentCard";
import { getCommerceData } from "@/lib/admin/server";
import type { AdminProductImage } from "@/lib/admin/types";
import { Link } from "@/i18n/navigation";
type Product = { id: number; nome: string; sku: string; descricaoCurta: string; descricao: string; preco: number; precoPromocional?: number; quantidadeEstoque: number; quantidadeReservada: number; estoqueMinimo: number; status: string; categoriaId: number | null; categoriaNome?: string | null; brandId?: number | null; brandName?: string | null };
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
export default async function Page({ params }: { params: Promise<{ id: string }> }) {
 const { id } = await params; const [product,images] = await Promise.all([getCommerceData<Product>(`/products/${id}`),getCommerceData<AdminProductImage[]>(`/products/${id}/images`)]); if (!product) return <ComponentCard title="Produto indisponível">Não foi possível carregar este produto.</ComponentCard>;
 return <main className="text-gray-800 dark:text-white/90"><Link href="/ecommerce/products" className="text-sm font-medium text-brand-500">← Produtos</Link><div className="mt-4 flex flex-wrap justify-between gap-3"><div><h1 className="text-title-md font-semibold">{product.nome}</h1><p className="text-sm text-gray-500 dark:text-gray-400">SKU: {product.sku}</p></div><span className="rounded-full bg-success-50 px-3 py-1 text-sm text-success-600 dark:bg-success-500/15">{product.status}</span></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><ComponentCard title="Informações"><dl className="grid grid-cols-2 gap-4 text-sm"><dt className="text-gray-500 dark:text-gray-400">Preço</dt><dd>{money(product.preco)}</dd><dt className="text-gray-500 dark:text-gray-400">Categoria</dt><dd>{product.categoriaNome ?? "Sem categoria"}</dd><dt className="text-gray-500 dark:text-gray-400">Marca</dt><dd>{product.brandName ?? "Sem marca"}</dd></dl></ComponentCard><ComponentCard title="Descrição"><p className="text-gray-700 dark:text-gray-200">{product.descricaoCurta}</p><p className="mt-3 text-gray-600 dark:text-gray-300">{product.descricao}</p></ComponentCard></div><ProductInventoryAndImages productId={product.id || Number(id)} initialStock={{ quantidadeEstoque: product.quantidadeEstoque, quantidadeReservada: product.quantidadeReservada, estoqueMinimo: product.estoqueMinimo }} initialImages={images ?? []}/></main>;
}
